Mobile View (Header + Content) ***Not including post-upload mobile view.
hirokazutei/visage-void pull request #15
Opened 2020-06-24 03:59 UTC by ibotforwin

This is the latest branch. I will be working on adding further mobile view to the image editing functionality.

2020-06-24 04:33 UTC, hirokazutei requested changes
I know it is still a WIP but I wanted to make sure that it is going to the right direction.
A complete mobile compatibility comes with more UI/UX and functional changes as well so I think the PR can just focus on the menu for now.

2020-06-24 04:33 UTC, hirokazutei commented on package.json
> +    "material-ui": "^0.20.2",
I don't think this dependency is needed.

2020-06-24 04:33 UTC, hirokazutei commented on src/components/Content/LeftPane/Dropzone.tsx
> +    },
I added a formatter/linter so if you can rebase against the updated master branch and run `yarn lint` it should remove the diffs.

2020-06-24 04:33 UTC, hirokazutei commented on src/components/Content/LeftPane/Dropzone.tsx
> +            </BrowserView>
I think if we want a distinct mobile view and browser view, we should split them into two-component declarations.

2020-06-24 04:33 UTC, hirokazutei commented on src/components/Content/index.tsx
> +        <BrowserView>
If the outer `div` style is the only difference, using `isMobile` to distinguish mobile devices and changing the style would avoid a lot of repeated code.

2020-06-24 04:33 UTC, hirokazutei commented on src/components/Content/LeftPane/Dropzone.tsx
> +            </BrowserView>
same as below:
If the outer div style is the only difference, using isMobile to distinguish mobile devices and changing the style would avoid a lot of repeated code.

2020-06-24 04:33 UTC, hirokazutei commented on src/components/Header/index.tsx
> +  const [anchorEl, setAnchorEl]= useState<true|false>(false);
I try to keep variable names reasonably verbose, so `anchorElement` is preferred.

2020-06-24 04:33 UTC, hirokazutei commented on src/components/Header/index.tsx
> +  const [anchorEl, setAnchorEl]= useState<true|false>(false);
typing should be `boolean`

2020-06-24 04:33 UTC, hirokazutei commented on src/components/Header/index.tsx
> +      open={Boolean(anchorEl)}
you shouldn't need to cast here.

2020-06-24 04:33 UTC, hirokazutei commented on src/components/Header/index.tsx
> +  <Button aria-controls="simple-menu" aria-haspopup="true" onClick={handleClick}>
Accessibility should be a whole other refactor so it can currently be dropped.

2020-06-24 04:33 UTC, hirokazutei commented on src/components/Header/index.tsx
> +      getContentAnchorEl={null}
I don't think id is needed and passing null into `getContentAnchorEl` causes a warning in the console.

2020-06-24 04:33 UTC, hirokazutei commented on src/components/Header/index.tsx
> +        <Title><div className='h3'>VISAGE VOID</div></Title>
Could you explain the `div` and class name?

2020-06-24 06:11 UTC, ibotforwin commented on src/components/Content/LeftPane/Dropzone.tsx
> +            </BrowserView>
Good point. Where differences are minor I'll use isMobile and otherwise separate components.

2022-08-21 01:49 UTC, ibotforwin commented
Wow, looking back this PR is kind of funny :D

2022-08-21 01:49 UTC, closed without merging